# Generated by Django 4.1.7 on 2023-02-22 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('fantasia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mercadologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, verbose_name='Código de Referencia')),
                ('superior', models.BigIntegerField(default=0, verbose_name='Código do Superior')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('parametro', models.BigIntegerField(null=True, verbose_name='Margem Parametro')),
                ('decimo', models.IntegerField(null=True, verbose_name='Ultimo Número')),
                ('ncm', models.CharField(max_length=8, null=True, verbose_name='NCM de referencia')),
            ],
        ),
        migrations.AddField(
            model_name='itens',
            name='composicao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itens',
            name='ncm',
            field=models.CharField(max_length=8, null=True, verbose_name='NCM'),
        ),
        migrations.AlterField(
            model_name='itens',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itens',
            name='barras',
            field=models.CharField(max_length=15, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='itens',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='itens',
            name='classificacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itens.mercadologica'),
        ),
    ]
