# Generated by Django 4.1.7 on 2023-02-24 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_empresa_mercadologica_itens_composicao_itens_ncm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens',
            name='classificacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itens.mercadologica'),
        ),
        migrations.AlterField(
            model_name='itens',
            name='ncm',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='NCM'),
        ),
        migrations.AlterField(
            model_name='mercadologica',
            name='decimo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ultimo Número'),
        ),
        migrations.AlterField(
            model_name='mercadologica',
            name='ncm',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='NCM de referencia'),
        ),
        migrations.AlterField(
            model_name='mercadologica',
            name='parametro',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Margem Parametro'),
        ),
        migrations.AlterField(
            model_name='mercadologica',
            name='superior',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Código do Superior'),
        ),
        migrations.CreateModel(
            name='ItensEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField(blank=True, null=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('barras', models.CharField(max_length=15, verbose_name='Código de Barras')),
                ('ativo', models.BooleanField(default=True)),
                ('composicao', models.BooleanField(default=False)),
                ('ncm', models.CharField(blank=True, max_length=8, null=True, verbose_name='NCM')),
                ('classificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itens.mercadologica')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itens.empresa')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itens.itens')),
            ],
        ),
    ]
