# Generated by Django 4.1.7 on 2023-03-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0003_alter_itens_classificacao_alter_itens_ncm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('barras', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código de Barras')),
                ('ativo', models.BooleanField(default=True)),
                ('composicao', models.BooleanField(default=False)),
                ('ncm', models.CharField(blank=True, max_length=8, null=True, verbose_name='NCM')),
                ('classificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itens.mercadologica')),
            ],
        ),
        migrations.CreateModel(
            name='ItemEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField(blank=True, null=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('barras', models.CharField(max_length=15, verbose_name='Código de Barras')),
                ('ativo', models.BooleanField(default=True)),
                ('composicao', models.BooleanField(default=False)),
                ('ncm', models.CharField(blank=True, max_length=8, null=True, verbose_name='NCM')),
                ('classificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itens.mercadologica', verbose_name='Classificação Mercadologica')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itens.empresa')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itens.item')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('detalhe', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='itensempresa',
            name='classificacao',
        ),
        migrations.RemoveField(
            model_name='itensempresa',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='itensempresa',
            name='item',
        ),
        migrations.DeleteModel(
            name='Itens',
        ),
        migrations.DeleteModel(
            name='ItensEmpresa',
        ),
        migrations.AddField(
            model_name='itemempresa',
            name='tag',
            field=models.ManyToManyField(to='itens.tag'),
        ),
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(to='itens.tag'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tag',
            field=models.ManyToManyField(to='itens.tag'),
        ),
        migrations.AddField(
            model_name='mercadologica',
            name='tag',
            field=models.ManyToManyField(to='itens.tag'),
        ),
    ]
