# Generated by Django 4.1.7 on 2023-05-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0004_item_itemempresa_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='tag',
            field=models.ManyToManyField(blank=True, to='itens.tag'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(blank=True, to='itens.tag'),
        ),
        migrations.AlterField(
            model_name='itemempresa',
            name='ncm',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='NCM'),
        ),
        migrations.AlterField(
            model_name='itemempresa',
            name='tag',
            field=models.ManyToManyField(blank=True, to='itens.tag'),
        ),
        migrations.AlterField(
            model_name='mercadologica',
            name='tag',
            field=models.ManyToManyField(blank=True, to='itens.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='detalhe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
